package com.fafen.survey.Util;

import com.fafen.survey.Util.Models.Constituencies;
import com.fafen.survey.Util.Models.Parties;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by andresrodriguez on 6/6/18.
 */

public class ListsData {


    private String[] cons = {
            "NA-1 Chitral",
            "NA-2 Swat-I",
            "NA-3 Swat-II",
            "NA-4 Swat-III",
            "NA-5 Upper Dir",
            "NA-6 Lower Dir-I",
            "NA-7 Lower Dir-II",
            "NA-8 Malakand Protected Area",
            "NA-9 Buner",
            "NA-10 Shangla",
            "NA-11 Kohistan-cum-Lower Kohistan-Cum-Kolai Pallas Kohistan",
            "NA-12 Battagram",
            "NA-13 Mansehra-I",
            "NA-14 Mansehra-cum-Torghar",
            "NA-15 Abbottabad-I",
            "NA-16 Abbottabad-II",
            "NA-17 Haripur",
            "NA-18 Swabi-I",
            "NA-19 Swabi-II",
            "NA-20 Mardan-I",
            "NA-21 Mardan-II",
            "NA-22 Mardan-III",
            "NA-23 Charsadda-I",
            "NA-24 Charsadda-II",
            "NA-25 Nowshera-I",
            "NA-26 Nowshera-II",
            "NA-27 Peshawar-I",
            "NA-28 Peshawar-II",
            "NA-29 Peshawar-III",
            "NA-30 Peshawar-IV",
            "NA-31 Peshawar-V",
            "NA-32 Kohat",
            "NA-33 Hangu",
            "NA-34 Karak",
            "NA-35 Bannu",
            "NA-36 Lakki Marwat",
            "NA-37 Tank",
            "NA-38 Dera Ismail Khan-I",
            "NA-39 Dera Ismail Khan-II",
            "NA-40 Bajaur Agency-I Tribal Area-I",
            "NA-41 Bajaur Agency-II Tribal Area-II",
            "NA-42 Mohmand Agency, Tribal Area Tribal Area-III",
            "NA-43 Khyber Agency-I Tribal Area-IV",
            "NA-44 Khyber Agency-II Tribal Area-V",
            "NA-45 Kurram Agency-I Tribal Area-VI",
            "NA-46 Kurram Agency-II, Tribal Area-VII",
            "NA-47 Orakzai Agency, Tribal Area-VIII",
            "NA-48 North Waziristan Agency, Tribal Area-IX",
            "NA-49 South Waziristan Agency-I Tribal Area-X",
            "NA-50 South Waziristan Agency-II Tribal Area-XI",
            "NA-51 Tribal Area-XII",
            "NA-52 Islamabad-I",
            "NA-53 Islamabad-II",
            "NA-54 Islamabad-III",
            "NA-55 Attock-I",
            "NA-56 Attock-II",
            "NA-57 Rawalpindi-I",
            "NA-58 Rawalpindi-II",
            "NA-59 Rawalpindi-III",
            "NA-60 Rawalpindi-IV",
            "NA-61 Rawalpindi-V",
            "NA-62 Rawalpindi-VI",
            "NA-63 Rawalpindi-VII",
            "NA-64 Chakwal-I",
            "NA-65 Chakwal-II",
            "NA-66 Jhelum-I",
            "NA-67 Jhelum-II",
            "NA-68 Gujrat-I",
            "NA-69 Gujrat-II",
            "NA-70 Gujrat-III",
            "NA-71 Gujrat-IV",
            "NA-72 Sialkot-I",
            "NA-73 Sialkot-II",
            "NA-74 Sialkot-III",
            "NA-75 Sialkot-IV",
            "NA-76 Sialkot-V",
            "NA-77 Narowal-I",
            "NA-78 Narowal-II",
            "NA-79 Gujranwala-I",
            "NA-80 Gujranwala-II",
            "NA-81 Gujranwala-III",
            "NA-82 Gujranwala-IV",
            "NA-83 Gujranwala-V",
            "NA-84 Gujranwala-VI",
            "NA-85 Mandi Bahauddin-I",
            "NA-86 Mandi Bahauddin-II",
            "NA-87 Hafizabad-I",
            "NA-88 Sargodha-I",
            "NA-89 Sargodha-II",
            "NA-90 Sargodha-III",
            "NA-91 Sargodha-IV",
            "NA-92 Sargodha-V",
            "NA-93 Khushab-I",
            "NA-94 Khushab-II",
            "NA-95 Mianwali-I",
            "NA-96 Mianwali-II",
            "NA-97 Bhakkar-I",
            "NA-98 Bhakkar-II",
            "NA-99 Chiniot-I",
            "NA-100 Chiniot-II",
            "NA-101 Faisalabad-I",
            "NA-102 Faisalabad-II",
            "NA-103 Faisalabad-III",
            "NA-104 Faisalabad-IV",
            "NA-105 Faisalabad-V",
            "NA-106 Faisalabad-VI",
            "NA-107 Faisalabad-VII",
            "NA-108 Faisalabad-VIII",
            "NA-109 Faisalabad-IX",
            "NA-110 Faisalabad-X",
            "NA-111 Toba Tek Singh-I",
            "NA-112 Toba Tek Singh-II",
            "NA-113 Toba Tek Singh-III",
            "NA-114 Jhang-I",
            "NA-115 Jhang-II",
            "NA-116 Jhang-III",
            "NA-117 Nankana Sahib-I",
            "NA-118 Nankana Sahib-II",
            "NA-119 Sheikhupura-I",
            "NA-120 Sheikhupura-II",
            "NA-121 Sheikhupura-III",
            "NA-122 Sheikhupura-IV",
            "NA-123 Lahore-I",
            "NA-124 Lahore-II",
            "NA-125 Lahore-III",
            "NA-126 Lahore-IV",
            "NA-127 Lahore-V",
            "NA-128 Lahore-VI",
            "NA-129 Lahore-VII",
            "NA-130 Lahore-VIII",
            "NA-131 Lahore-IX",
            "NA-132 Lahore-X",
            "NA-133 Lahore-XI",
            "NA-134 Lahore-XII",
            "NA-135 Lahore-XIII",
            "NA-136 Lahore-XIV",
            "NA-137 Kasur-I",
            "NA-138 Kasur-II",
            "NA-139 Kasur-III",
            "NA-140 Kasur-IV",
            "NA-141 Okara-I",
            "NA-142 Okara-II",
            "NA-143 Okara-III",
            "NA-144 Okara-IV",
            "NA-145 Pakpattan-I",
            "NA-146 Pakpattan-II",
            "NA-147 Sahiwal-I",
            "NA-148 Sahiwal-II",
            "NA-149 Sahiwal-III",
            "NA-150 Khanewal-I",
            "NA-151 Khanewal-II",
            "NA-152 Khanewal-III",
            "NA-153 Khanewal-IV",
            "NA-154 Multan-I",
            "NA-155 Multan-II",
            "NA-156 Multan-III",
            "NA-157 Multan-IV",
            "NA-158 Multan-V",
            "NA-159 Multan-VI",
            "NA-160 Lodhran-I",
            "NA-161 Lodhran-II",
            "NA-162 Vehari-I",
            "NA-163 Vehari-II",
            "NA-164 Vehari-III",
            "NA-165 Vehari-IV",
            "NA-166 Bahawalnagar-I",
            "NA-167 Bahawalnagar-II",
            "NA-168 Bahawalnagar-III",
            "NA-169 Bahawalnagar-IV",
            "NA-170 Bahawalpur-I",
            "NA-171 Bahawalpur-II",
            "NA-172 Bahawalpur-III",
            "NA-173 Bahawalpur-IV",
            "NA-174 Bahawalpur-V",
            "NA-175 Rahim Yar Khan-I",
            "NA-176 Rahim Yar Khan-II",
            "NA-177 Rahim Yar Khan-III",
            "NA-178 Rahim Yar Khan-IV",
            "NA-179 Rahim Yar Khan-V",
            "NA-180 Rahim Yar Khan-VI",
            "NA-181 Muzaffargarh-I",
            "NA-182 Muzaffargarh-II",
            "NA-183 Muzaffargarh-III",
            "NA-184 Muzaffargarh-IV",
            "NA-185 Muzaffargarh-V",
            "NA-186 Muzaffargarh-VI",
            "NA-187 Layyah-I",
            "NA-188 Layyah-II",
            "NA-189 Dera Ghazi Khan-I",
            "NA-190 Dera Ghazi Khan-II",
            "NA-191 Dera Ghazi Khan-III",
            "NA-192 Dera Ghazi Khan-IV",
            "NA-193 Rajanpur-I",
            "NA-194 Rajanpur-II",
            "NA-195 Rajanpur-III",
            "NA-196 Jacobabad",
            "NA-197 Kashmore",
            "NA-198 Shikarpur-I",
            "NA-199 Shikarpur-II",
            "NA-200 Larkana-I",
            "NA-201 Larkana-II",
            "NA-202 Kamber Shahdadkot-I",
            "NA-203 Kamber Shahdadkot-II",
            "NA-204 Ghotki-I",
            "NA-205 Ghotki-II",
            "NA-206 Sukkur-I",
            "NA-207 Sukkur-II",
            "NA-208 Khairpur-I",
            "NA-209 Khairpur-II",
            "NA-210 Khairpur-III",
            "NA-211 Nausharo Feroze-I",
            "NA-212 Nausharo Feroze-II",
            "NA-213 Shaheed Benazirabad-I",
            "NA-214 Shaheed Benazirabad-II",
            "NA-215 Sanghar-I",
            "NA-216 Sanghar-II",
            "NA-217 Sanghar-III",
            "NA-218 Mirpurkhas-I",
            "NA-219 Mirpurkhas-II",
            "NA-220 Umerkot",
            "NA-221 Tharparkar-I",
            "NA-222 Tharparkar-II",
            "NA-223 Matiari",
            "NA-224 Tando Allahyar",
            "NA-225 Hyderabad-I",
            "NA-226 Hyderabad-II",
            "NA-227 Hyderabad-III",
            "NA-228 Tando Muhammad Khan",
            "NA-229 Badin-I",
            "NA-230 Badin-II",
            "NA-231 Sujawal",
            "NA-232 Thatta",
            "NA-233 Jamshoro",
            "NA-234 Dadu-I",
            "NA-235 Dadu-II",
            "NA-236 Malir-I",
            "NA-237 Malir-II",
            "NA-238 Malir-III",
            "NA-239 Korangi Karachi-I",
            "NA-240 Korangi Karachi-II",
            "NA-241 Korangi Karachi-III",
            "NA-242 Karachi East-I",
            "NA-243 Karachi East-II",
            "NA-244 Karachi East-III",
            "NA-245 Karachi East-IV",
            "NA-246 Karachi South-I",
            "NA-247 Karachi South-II",
            "NA-248 Karachi West-I",
            "NA-249 Karachi West-II",
            "NA-250 Karachi West-III",
            "NA-251 Karachi West-IV",
            "NA-252 Karachi West-V",
            "NA-253 Karachi Central-I",
            "NA-254 Karachi Central-II",
            "NA-255 Karachi Central-III",
            "NA-256 Karachi Central-IV",
            "NA-257 Killa Saifullah-cum-Zhob-cum-Sherani",
            "NA-258 Loralai-cum-Musa Khail-cum-Ziarat-cum-Dukki-cum-Harnai",
            "NA-259 Dera Bugti-cum-Kohlu-cum-Barkhan-cum-Sibi-cum-Lehri",
            "NA-260 Nasirabad-cum-Kachhi-cum-Jhal Magsi",
            "NA-261 Jafarabad-cum-Sohbatpur",
            "NA-262 Pishin",
            "NA-263 Killa Abdullah",
            "NA-264 Quetta-I",
            "NA-265 Quetta-II",
            "NA-266 Quetta-III",
            "NA-267 Mastung-cum-Shaheed Sikandarabad-cum-Kalat",
            "NA-268 Chagai-cum-Nushki-cum-Kharan",
            "NA-269 Khuzdar",
            "NA-270 Panjgur-cum-Washuk-cum-Awaran",
            "NA-271 Kech",
            "NA-272 Lasbela-cum-Gwadar"
    };

    private String[] parties = {
            "All Pakistan Muslim League",
            "Awami Justice Party Pakistan",
            "Awami Muslim League Pakistan",
            "Awami National Party",
            "Awami Workers Party",
            "Bahawalpur National Awami Party",
            "Balochistan National Party (Awami)",
            "Balochistan National Party",
            "Hazara Democratic Party",
            "Independent",
            "Islami Tehreek Pakistan",
            "Jamaat-e-Islami Pakistan",
            "Jamhoori Wattan Party",
            "Jamiat Ulama-e-Islam (Fazal Ur Rehman)",
            "Jamiat Ulama-e-Islam Nazryati Pakistan",
            "Jamiat Ulama-e-Islam (Sami -ul-Haq)",
            "Jamiat Ulma-e-Pakistan (Noorani)",
            "Jamote Qami Movement",
            "Jannat Pakistan Party",
            "Majlis-e-Wahdat-e-Muslimeen Pakistan",
            "Mohajar Qaumi Movement Pakistan",
            "Mohib-e-Wattan Nowjawan Inqilabion Ki Anjuman",
            "Mustaqbil Pakistan",
            "Mutahidda Qabil Party",
            "Muttahidda Qaumi Movement",
            "National Party",
            "National Peoples Party",
            "Pakistan Conservative Party",
            "Pakistan Falah Party",
            "Pakistan Human Rights Party",
            "Pakistan Muhafiz Watan Party",
            "Pakistan Muslim League Council",
            "Pakistan Muslim League (Functional)",
            "Pakistan Muslim League (Nawaz)",
            "Pakistan Muslim League",
            "Pakistan Muslim League (Sher-e-Bangal) A.K. Fazal-Ul-Haque)",
            "Pakistan Muslim League (Zia)",
            "Pakistan National Muslim League",
            "Pakistan Peoples Party Parliamentarians",
            "Pakistan Peoples Party (Shaheed Bhutto)",
            "Pakistan Sunni Tehreek",
            "Pakistan Tehreek-e-Insaf",
            "Qaumi Watan Party (Sherpao)",
            "Sindh United Party",
            "Sunni Ittehad Council",
            "Tehreek-e-Suba Hazara",
            "Tehreek-e-Tahaffuze Pakistan",
            "Tehreek Tabdili Nizam Pakistan",
            "Pakistan Awami Tehreek",
            "Nizam-e-Mustafa Party",
            "Sunni Tehreek",
            "Balochistan National Movement",
            "Pakistan Citizen Movement",
            "Pakistan Aman Party",
            "Pasban",
            "Pakistan Muslim League Jinnah",
            "Pakistan Rah-e-Haq Party",
            "Peoples Muslim League Pakistan",
            "Markazi Jamiat Al- Hadith (Sajid Mir)",
            "Pakistan People's Party",
            "Tehreek-e-Labaik Pakistan",
            "Front National Pakistan",
            "Allah-o-Akbar Tehreek",
            "Aam Admi Tehreek Pakistan",
            "Aam Awam Party",
            "Aam Loeg Ittehad",
            "Aam Log Party Pakistan",
            "All Pakistan Minorities Alliance",
            "All Pakistan Minority Movement",
            "All Pakistan Muslim League - Jinnah",
            "All Pakistan Tehreek",
            "Amun Taraqqi Party",
            "Awam League",
            "Barabri Party Pakistan",
            "Humdardan-e-Watan Pakistan",
            "Masih Awami Party",
            "Mutihida League",
            "Muttahidda Ulema-e-Mashaikh Council of Pakistan",
            "National Peace Council Party",
            "Pak Sarzameen Party",
            "Pakistan Aman Tehreek",
            "Pakistan Awami Raj",
            "Pakistan Barabri Party",
            "Pakistan Falahi Tehreek",
            "Pakistan Freedom Movement",
            "Pakistan Human Party",
            "Pakistan Islamic Republican Party",
            "Pakistan Justice & Democratic Party",
            "Pakistan Kissan Ittehad (Ch. Anwar)",
            "Pakistan Masiha Party",
            "Pakistan Muslim Alliance",
            "Pakistan Peoples Party Workers",
            "Pakistan Supreme Democratic Party",
            "Pakistan Tehreek-e-Ijtihad",
            "Pakistan Tehreek-e-Insaf Nazriati",
            "Pakistan Tehreek-e-Insaniat",
            "Pakistan Welfare Party",
            "Pakistan Yaqeen Party",
            "Pashtoonkhwa Milli Awami Party",
            "Peoples Movement of Pakistan",
            "Roshan Pakistan League",
            "Tabdeeli Pasand Party",
            "Tehreek Ahle-e-Sunnat Pakistan",
            "Tehreek Jawanan Pakistan",
            "Tehreek-e-Difa-e-Pakistan",
            "Tehreek-e-Ehsas-e-Pakistan",
            "Tehreek-e-Labbaik Islam",
            "Islami Jamhoori Ittehad Pakistan",
            "Ittehad-e-Ummat Pakistan",
            "Pakistan Awami League",
            "Pakistan Quami Yakjehti Party"
    };

    private String[] newParties = {
            "Independent",
            "Aam Admi Tehreek Pakistan",
            "Aam Awam Party",
            "Aam Log Party Pakistan",
            "All Pakistan Minority Movement",
            "All Pakistan Muslim League",
            "All Pakistan Muslim League - Jinnah",
            "All Pakistan Tehreek",
            "Allah-o-Akbar Tehreek",
            "Amun Taraqqi Party",
            "Awam League",
            "Awami Justice Party Pakistan",
            "Awami Muslim League Pakistan",
            "Awami National Party",
            "Awami Party Pakistan-S",
            "Awami Workers Party",
            "Balochistan Awami Party",
            "Balochistan National Movement",
            "Balochistan National Party",
            "Balochistan National Party (Awami)",
            "Barabri Party Pakistan",
            "Front National Pakistan",
            "Grand Democratic Alliance",
            "Hazara Democratic Party",
            "Humdardan-e-Watan Pakistan",
            "Islami Jamhoori Ittehad Pakistan",
            "Islami Tehreek Pakistan",
            "Ittehad-e-Ummat Pakistan",
            "Jamat-e-Islami Pakistan",
            "Jamhoori Wattan Party",
            "Jamiat Ulama-e-Islam Nazryati Pakistan",
            "Jamiat Ulama-e-Islam (Fazal Ur Rehman)",
            "Jamiat Ulma-e-Pakistan (Noorani)",
            "Jamiat Ulama-e-Islam (Sami -ul-Haq)",
            "Jamote Qaumi Movement",
            "Jannat Pakistan Party",
            "Majlis-e-Wahdat-e-Muslimeen Pakistan",
            "Markazi Jamiat Ahl-e-Hadith Pakistan",
            "Mohajar Qaumi Movement Pakistan",
            "Move on Pakistan",
            "Mohib-e-Wattan Nowjawan Inqilabion Ki Anjuman",
            "Mustaqbil Pakistan",
            "Muttahidda Majlis-e-Amal Pakistan",
            "Muttahidda Ulema-e-Mashaikh Council of Pakistan",
            "Mutahidda Qabail Party",
            "Mutihida League",
            "Muttahidda Qaumi Movement",
            "National Party",
            "National Peace Council Party",
            "Pak Sarzameen Party",
            "Pashtunkhwa Milli Awami Party",
            "Pakistan Aman Party",
            "Pakistan Aman Tehreek",
            "Pakistan Awami Inqelabi League",
            "Pakistan Awami League",
            "Pakistan Awami Raj",
            "Pakistan Awami Tehreek",
            "Pakistan Citizen Movement",
            "Pakistan Conservative Party",
            "Pakistan Falah Party",
            "Pakistan Falahi Tehreek",
            "Pakistan Freedom Movement",
            "Pakistan Human Party",
            "Pakistan Human Rights Party",
            "Pakistan Islamic Republican Party",
            "Pakistan Justice & Democratic Party",
            "Pakistan Kissan Ittehad (Ch. Anwar)",
            "Pakistan Muslim Alliance",
            "Pakistan Muslim League",
            "Pakistan Muslim League Council",
            "Pakistan Muslim League (Functional)",
            "Pakistan Muslim League (Junejo)",
            "Pakistan Muslim League (Nawaz)",
            "Pakistan Muslim League (Zia)",
            "Pakistan Muslim League Organization",
            "Pakistan People's Party",
            "Pakistan Peoples Party (Shaheed Bhutto)",
            "Pakistan Peoples Party Parliamentarians",
            "Pakistan Peoples Party Workers",
            "Pakistan Quami Yakjehti Party",
            "Pakistan Rah-e-Haq Party",
            "Pakistan Sunni Tehreek",
            "Pakistan Supreme Democratic Party",
            "Pakistan Tehreek-e-Insaf",
            "Pakistan Tehreek-e-Insaf Nazriati",
            "Pakistan Tehreek-e-Insaf-Gulalai",
            "Pakistan Tehreek-e-Insaniat",
            "Pakistan Welfare Party",
            "Pakistan Yaqeen Party",
            "Pasban",
            "Peoples Movement of Pakistan",
            "Peoples Muslim League Pakistan",
            "Qaumi Watan Party (Sherpao)",
            "Roshan Pakistan League",
            "Saraikistan Democratic Party",
            "Sindh United Party",
            "Sunni Ittehad Council",
            "Sunni Tehreek",
            "Tabdeeli Pasand Party",
            "Tehreek-e-Labaik Pakistan",
            "Tehreek Tabdili Nizam Pakistan",
            "Tehreek-e-Difa-e-Pakistan",
            "Tehreek-e-Labbaik Islam",
            "Tehreek Jawanan Pakistan"
    };

    private String[] districts = {
            "Chitral",
            "Swat",
            "Upper Dir",
            "Lower Dir",
            "Malakand",
            "Buner",
            "Shangla",
            "Kohistan",
            "Batagram",
            "Mansehra",
            "Tor Ghar",
            "Abbottabad",
            "Haripur",
            "Swabi",
            "Mardan",
            "Charsadda",
            "Nowshera",
            "Peshawar",
            "Kohat",
            "Hangu",
            "Karak",
            "Bannu",
            "Lakki Marwat",
            "Tank",
            "Dera Ismail Khan",
            "Bajaur Agency",
            "Mohmand Agency",
            "Khyber Agency",
            "Kurram Agency",
            "Orakzai Agency",
            "North Waziristan Agency",
            "South Waziristan Agency",
            "Islamabad",
            "Attock",
            "Rawalpindi",
            "Chakwal",
            "Jhelum",
            "Gujrat",
            "Sialkot",
            "Narowal",
            "Gujranwala",
            "Mandi Bahauddin",
            "Hafizabad",
            "Sargodha",
            "Khushab",
            "Mianwali",
            "Bhakkar",
            "Chiniot",
            "Faisalabad",
            "Toba Tek Singh",
            "Jhang",
            "Nankana Sahib",
            "Sheikhupura",
            "Lahore",
            "Kasur",
            "Okara",
            "Pakpattan",
            "Sahiwal",
            "Khanewal",
            "Multan",
            "Lodhran",
            "Vehari",
            "Bahawalnagar",
            "Bahawalpur",
            "Rahim Yar Khan",
            "Muzaffargarh",
            "Layyah",
            "Dera Ghazi Khan",
            "Rajanpur",
            "Jacobabad",
            "Kashmore",
            "Shikarpur",
            "Larkana",
            "Kamber Shahdadkot",
            "Ghotki",
            "Sukkur",
            "Khairpur",
            "Naushero Feroz",
            "Shaheed Benazirabad",
            "Sanghar",
            "Mirpurkhas",
            "Umerkot",
            "Tharparkar",
            "Matiari",
            "Tando Allahyar",
            "Hyderabad",
            "Tando Muhammad Khan",
            "Badin",
            "Sujawal",
            "Thatta",
            "Jamshoro",
            "Dadu",
            "Malir",
            "Korangi",
            "Karachi East",
            "Karachi South",
            "Karachi West",
            "Karachi Central",
            "Killa Saifullah",
            "Zhob",
            "Sherani",
            "Loralai",
            "Musakhel",
            "Ziarat",
            "Harnai",
            "Dera Bugti",
            "Kohlu",
            "Barkhan",
            "Sibi",
            "Lehri",
            "Nasirabad",
            "Kachhi",
            "Jhal Magsi",
            "Jaffarabad",
            "Sohbatpur",
            "Pishin",
            "Killa Abdullah",
            "Quetta",
            "Mastung",
            "Kalat",
            "Chagai",
            "Nushki",
            "Kharan",
            "Khuzdar",
            "Panjgur",
            "Washuk",
            "Awaran",
            "Kech",
            "Lasbela",
            "Gwadar"
    };

    public String[] getCons() {
        return cons;
    }

    public String[] getParties() {
        return parties;
    }

    public String[] getDistricts() {
        return districts;
    }

    private List<Constituencies> consList = new ArrayList<Constituencies>();
    private List<Parties> partiesList = new ArrayList<Parties>();

    public List<Constituencies> getConstituencies(){

        consList = new ArrayList<Constituencies>();
        consList.add(new Constituencies(3011,"NA-1 Chitral","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3012,"NA-2 Swat-I","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3013,"NA-3 Swat-II","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3014,"NA-4 Swat-III","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3015,"NA-5 Upper Dir","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3016,"NA-6 Lower Dir-I","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3017,"NA-7 Lower Dir-II","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3018,"NA-8 Malakand Protected Area","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3019,"NA-9 Buner","National","Khyber Pakhtunkhwa",4,"Malakand"));
        consList.add(new Constituencies(3020,"NA-10 Shangla","National","Khyber Pakhtunkhwa",4,"Malakand"));


        return null;
    }

    public String[] getNewParties() {
        return newParties;
    }
}
